### ISSUE TITLE
What are the differences between the "with onnx" compilation and the official version during cmake?

### ISSUE THREAD

**Issue by ZJDATY** [zihaomu/opencv_lite#1]
I know that the native DNN supports reading models from onnx, so why choose "with onnx" during compilation? Which onnx operators can it specifically support?

**Comment by zihaomu** [comment]
Yes, the native DNN can support ONNX model, but not all ONNX model. There are always models trained by users but not supported by OpenCV. The ONNX operator cover rate is an important metric number. In this project, we try to introduce the native ONNXRuntime lib to OpenCV DNN API. So, the cover rate is the same as ONNXRuntime. You can think that `opencv_ort` can support all ONNX Op. That's the basic idea.
